window.MULAB_GALLERY = {
  "timeline": [
    {
      "id": "local_event_2026_007",
      "src": "Gallery/date_pending_existing/amanda-birthday-july-2026.jpg",
      "date": "July 2026",
      "sortDate": "2026-07-01",
      "year": "2026",
      "precision": "month",
      "title": "Amanda’s Birthday",
      "caption": "Mu Lab celebrating Amanda’s birthday!",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1800,
      "height": 1350
    },
    {
      "id": "local_event_2026_006",
      "src": "Gallery/date_pending_existing/pending_06_图片_20260627151557_69_27.jpg",
      "date": "2026",
      "sortDate": "2026-01-01",
      "year": "2026",
      "precision": "year",
      "title": "Yuyin’s Last Day",
      "caption": "A group selfie celebrating Yuyin’s last day in the lab — an outstanding lab manager, researcher, colleague, and friend.",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1706,
      "height": 1279
    },
    {
      "id": "local_event_2026_004",
      "src": "Gallery/date_pending_existing/pending_04_图片_20260627151555_67_27.jpg",
      "date": "2026",
      "sortDate": "2026-01-01",
      "year": "2026",
      "precision": "year",
      "title": "Yaru received the NCI K99/R00!",
      "caption": "Yaru received NCI K99/R00 award on the first submission!",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1279,
      "height": 1706
    },
    {
      "id": "local_event_2026_001",
      "src": "Gallery/date_pending_existing/pending_01_图片_20260627151551_64_27.jpg",
      "date": "2026",
      "sortDate": "2026-01-01",
      "year": "2026",
      "precision": "year",
      "title": "Yale Prostate Cancer Symposium",
      "caption": "Zirui presenting her poster",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1706,
      "height": 1279
    },
    {
      "id": "local_event_2026_002",
      "src": "Gallery/date_pending_existing/pending_02_图片_20260627151552_65_27.jpg",
      "date": "2026",
      "sortDate": "2026-01-01",
      "year": "2026",
      "precision": "year",
      "title": "Yale Prostate Cancer Symposium",
      "caption": "Siyuan was selected as post winner!",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1279,
      "height": 1662
    },
    {
      "id": "local_event_2026_003",
      "src": "Gallery/date_pending_existing/pending_03_图片_20260627151553_66_27.jpg",
      "date": "2026",
      "sortDate": "2026-01-01",
      "year": "2026",
      "precision": "year",
      "title": "Yale Prostate Cancer Symposium",
      "caption": "Siyuan in discussion with Dr. Sawyers",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1279,
      "height": 1706
    },
    {
      "id": "local_event_2026_005",
      "src": "Gallery/date_pending_existing/pending_05_图片_20260627151556_68_27.jpg",
      "date": "2026",
      "sortDate": "2026-01-01",
      "year": "2026",
      "precision": "year",
      "title": "Yale Prostate Cancer Symposium",
      "caption": "Melanie was selected as post winner!",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1706,
      "height": 1279
    },
    {
      "id": "local_event_2025_004",
      "src": "Gallery/date_pending_existing/pending_10_图片_20260627152527_79_27.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Secret Santa gift exchange",
      "caption": "Secret Santa gift exchange",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1706,
      "height": 1279
    },
    {
      "id": "curated_event_045",
      "src": "Gallery/curated_lab_events_by_year/2025/011_dated_2025-12_mu-lab-secret-santa-gift-exchange-2025_yale.jpg",
      "date": "2025-12",
      "sortDate": "2025-12-01",
      "year": "2025",
      "precision": "month/event",
      "title": "Mu Lab Secret Santa gift exchange 2025",
      "caption": "Mu Lab Secret Santa gift exchange 2025",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/3bfdaa9a-ea88-4fb1-ba5d-0170a579ba00",
      "width": 3000,
      "height": 2250
    },
    {
      "id": "curated_event_044",
      "src": "Gallery/curated_lab_events_by_year/2025/010_dated_2025-12_december-2025-department-christmas-party_yale.jpg",
      "date": "2025-12",
      "sortDate": "2025-12-01",
      "year": "2025",
      "precision": "month/event",
      "title": "December 2025: Department Christmas Party",
      "caption": "December 2025: Department Christmas Party",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/925aeb42-e3dc-495b-9ccb-f0ff68d1f94e",
      "width": 3000,
      "height": 2729
    },
    {
      "id": "curated_event_040",
      "src": "Gallery/curated_lab_events_by_year/2025/006_manual-order_2025_ping-mu-phd-with-the-students_yale.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Ping Mu, PhD, with the students",
      "caption": "Ping Mu, PhD, with the students celebrating the holidays 2025",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/3677f41d-ecac-4b1e-ae03-bab5fab5e9bb",
      "width": 1440,
      "height": 1080
    },
    {
      "id": "local_event_2025_002",
      "src": "Gallery/date_pending_existing/pending_08_图片_20260627152524_77_27.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Mu Lab holiday gathering",
      "caption": "Celebrating the holidays!",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1448,
      "height": 1279
    },
    {
      "id": "local_event_2025_005",
      "src": "Gallery/date_pending_existing/pending_11_图片_20260627152848_80_27.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Mu Lab gathering",
      "caption": "Mu Lab gathering",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1706,
      "height": 1279
    },
    {
      "id": "local_event_2025_003",
      "src": "Gallery/date_pending_existing/pending_09_图片_20260627152525_78_27.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Mu Lab dinner",
      "caption": "Mu Lab dinner",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1706,
      "height": 1279
    },
    {
      "id": "local_event_2025_007",
      "src": "Gallery/date_pending_existing/pending_13_图片_20260627152850_82_27.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Mu Lab gathering",
      "caption": "Mu Lab gathering",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1707,
      "height": 1279
    },
    {
      "id": "curated_event_043",
      "src": "Gallery/curated_lab_events_by_year/2025/009_manual-order_2025_summer-student-poster-presentation_yale.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Summer student poster presentation",
      "caption": "Summer student poster presentation",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/8927ae42-37b5-463c-895d-dba5e05722a0",
      "width": 722,
      "height": 744
    },
    {
      "id": "curated_event_042",
      "src": "Gallery/curated_lab_events_by_year/2025/008_manual-order_2025_rotation-talk-featuring-zirui_yale.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Rotation talk featuring Zirui",
      "caption": "Rotation talk featuring Zirui",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/22aaacb2-2e65-4290-92e9-dc14fd1a17ad",
      "width": 1173,
      "height": 880
    },
    {
      "id": "curated_event_041",
      "src": "Gallery/curated_lab_events_by_year/2025/007_manual-order_2025_poster-presentation-at-program-in-translational-biomedicine-ptb-retreat-featuring-me_yale.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Poster presentation at Program in Translational BioMedicine (PTB) retreat featuring Melanie",
      "caption": "Poster presentation at Program in Translational BioMedicine (PTB) retreat featuring Melanie",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/8b32e5b8-a6a0-4987-a0ae-cb4e8282d748",
      "width": 653,
      "height": 871
    },
    {
      "id": "local_event_2025_001",
      "src": "Gallery/date_pending_existing/pending_07_图片_20260627152324_75_27.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Christo & Longjun",
      "caption": "Christo with his great mentor Longjun!",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1279,
      "height": 1707
    },
    {
      "id": "curated_event_039",
      "src": "Gallery/curated_lab_events_by_year/2025/005_manual-order_2025_new-student-christo-joining-mu-lab_yale.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "New student, Christo, joining Mu lab",
      "caption": "New student, Christo, joining Mu lab",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/472e2474-7985-4a7f-9670-0fb4161435fd",
      "width": 2250,
      "height": 3000
    },
    {
      "id": "curated_event_038",
      "src": "Gallery/curated_lab_events_by_year/2025/004_manual-order_2025_mu-lab-celebrating-end-of-training-for-summer-students_yale.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Mu Lab celebrating end of training for summer students",
      "caption": "Mu Lab celebrating end of training for summer students",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/d5ac878d-e04d-4927-8522-b4ef42577a8b",
      "width": 3000,
      "height": 1485
    },
    {
      "id": "curated_event_037",
      "src": "Gallery/curated_lab_events_by_year/2025/003_manual-order_2025_mu-lab-celebrating-siyuans-birthday_yale.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Mu Lab celebrating Siyuan’s birthday",
      "caption": "Mu Lab celebrating Siyuan’s birthday",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/3595929d-a2e1-433b-86d2-c7bbdce04c41",
      "width": 648,
      "height": 864
    },
    {
      "id": "curated_event_036",
      "src": "Gallery/curated_lab_events_by_year/2025/002_manual-order_2025_mu-lab-plenary-session-2025-prostate-cancer-foundation-annual-meeting-san-diego_yale.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Mu Lab - Plenary Session, 2025 Prostate Cancer Foundation Annual Meeting, San Diego",
      "caption": "Mu Lab - Plenary Session, 2025 Prostate Cancer Foundation Annual Meeting, San Diego",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/e12a7482-043e-4af4-aef6-65c920abdad5",
      "width": 767,
      "height": 1024
    },
    {
      "id": "local_event_2025_008",
      "src": "Gallery/date_pending_existing/pending_14_图片_20260627153053_83_27.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "2025 Prostate Cancer Foundation Annual  Meeting, San Diego",
      "caption": "Plenary Session, 2025 Prostate Cancer Foundation Annual Meeting, San Diego",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1916,
      "height": 1279
    },
    {
      "id": "curated_event_035",
      "src": "Gallery/curated_lab_events_by_year/2025/001_manual-order_2025_mu-lab-2025-aacr-annual-meeting-chicago_yale.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "Mu Lab - 2025 AACR Annual Meeting, Chicago",
      "caption": "Mu Lab - 2025 AACR Annual Meeting, Chicago",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/7823df4e-c88d-4a3a-8198-7308e2809f31",
      "width": 1024,
      "height": 800
    },
    {
      "id": "local_event_2025_009",
      "src": "Gallery/date_pending_existing/pending_15_图片_20260627153056_84_27.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "2025 Donnini-Rudolph Family Foundation – PCF Challenge Award",
      "caption": "2025 Donnini-Rudolph Family Foundation – PCF Challenge Award",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1916,
      "height": 1279
    },
    {
      "id": "local_event_2025_010",
      "src": "Gallery/date_pending_existing/pending_16_图片_20260627153512_85_27.jpg",
      "date": "2025",
      "sortDate": "2025-01-01",
      "year": "2025",
      "precision": "year",
      "title": "2025 Urological Research Society Meeting in Kyoto",
      "caption": "The Department of Urology at Yale is excited to present our latest work at the 2025 Urological Research Society (URS) Meeting in Kyoto, a fantastic site for fantastic science.",
      "source": "Mu Lab",
      "descriptionSource": "Local",
      "sourceUrl": "",
      "width": 1279,
      "height": 1520
    },
    {
      "id": "curated_event_034",
      "src": "Gallery/curated_lab_events_by_year/2024/010_dated_2024-12_mu-lab-is-celebrating-christmas-together_yale.jpg",
      "date": "2024-12",
      "sortDate": "2024-12-01",
      "year": "2024",
      "precision": "month/event",
      "title": "Mu lab is celebrating Christmas together",
      "caption": "Mu lab is celebrating Christmas together.",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/8de94a30-8d1b-4b57-ad4e-38779b8201a7",
      "width": 2978,
      "height": 1984
    },
    {
      "id": "curated_event_033",
      "src": "Gallery/curated_lab_events_by_year/2024/009_dated_2024-12_december-2024-mu-lab-having-first-christmas-dinner-in-connecticut_yale.jpg",
      "date": "2024-12",
      "sortDate": "2024-12-01",
      "year": "2024",
      "precision": "month/event",
      "title": "December 2024: Mu Lab having first Christmas dinner in Connecticut",
      "caption": "December 2024: Mu Lab having first Christmas dinner in Connecticut",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/78bdef6c-fc73-4ad5-9d88-ddc42d80be77",
      "width": 3000,
      "height": 2250
    },
    {
      "id": "curated_event_032",
      "src": "Gallery/curated_lab_events_by_year/2024/008_dated_2024-12_2024-urology-department-holiday-party_yale.jpg",
      "date": "2024-12",
      "sortDate": "2024-12-01",
      "year": "2024",
      "precision": "month/event",
      "title": "2024 Urology Department Holiday Party",
      "caption": "2024 Urology Department Holiday Party",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/1a8634c3-79f0-4fc2-9bf3-a577755780a4",
      "width": 1740,
      "height": 1305
    },
    {
      "id": "curated_event_031",
      "src": "Gallery/curated_lab_events_by_year/2024/007_dated_2024-11_november-2024-celebrating-first-thanksgiving-in-connecticut_yale.jpg",
      "date": "2024-11",
      "sortDate": "2024-11-01",
      "year": "2024",
      "precision": "month/event",
      "title": "November 2024: Celebrating first Thanksgiving in Connecticut",
      "caption": "November 2024: Celebrating first Thanksgiving in Connecticut",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/cd146e7d-6260-4f4e-964c-a30686a455ea",
      "width": 1740,
      "height": 1305
    },
    {
      "id": "curated_event_030",
      "src": "Gallery/curated_lab_events_by_year/2024/006_manual-order_2024_we-are-celebrating-the-acceptance-of-our-4th-paper-on-cancer-discovery_yale.jpg",
      "date": "2024",
      "sortDate": "2024-01-01",
      "year": "2024",
      "precision": "year",
      "title": "We are celebrating the acceptance of our 4th paper on Cancer Discovery",
      "caption": "We are celebrating the acceptance of our 4th paper on Cancer Discovery",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/a68ed353-7c72-4773-992b-04bef6002f62",
      "width": 3000,
      "height": 2262
    },
    {
      "id": "curated_event_029",
      "src": "Gallery/curated_lab_events_by_year/2024/005_manual-order_2024_mu-lab-at-the-aacr-2024-annual-meeting_yale.jpg",
      "date": "2024",
      "sortDate": "2024-01-01",
      "year": "2024",
      "precision": "year",
      "title": "Mu lab at the AACR 2024 annual meeting",
      "caption": "Mu lab at the AACR 2024 annual meeting.",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/2e4c010c-bf8f-4a7f-9852-7e38557bd992",
      "width": 3000,
      "height": 2250
    },
    {
      "id": "curated_event_028",
      "src": "Gallery/curated_lab_events_by_year/2024/004_manual-order_2024_graduation-ceremony-for-our-awesome-student-carla_yale.jpg",
      "date": "2024",
      "sortDate": "2024-01-01",
      "year": "2024",
      "precision": "year",
      "title": "Graduation Ceremony for Our Awesome Student Carla",
      "caption": "Graduation Ceremony for Our Awesome Student Carla",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/c90130b2-c6fe-49e6-b03b-7319733d064e",
      "width": 1714,
      "height": 1557
    },
    {
      "id": "curated_event_027",
      "src": "Gallery/curated_lab_events_by_year/2024/003_manual-order_2024_dr-ping-mu-presenting-our-work-at-the-embo-meeting-in-rimini-italy_yale.jpg",
      "date": "2024",
      "sortDate": "2024-01-01",
      "year": "2024",
      "precision": "year",
      "title": "Dr. Ping Mu presenting our work at the EMBO meeting in Rimini, Italy.",
      "caption": "Dr. Ping Mu presenting our work at the EMBO meeting in Rimini, Italy.",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/2f7b26d5-3713-4d30-a2b4-9a219ab41a50",
      "width": 3000,
      "height": 1934
    },
    {
      "id": "curated_event_026",
      "src": "Gallery/curated_lab_events_by_year/2024/002_manual-order_2024_congratulating-choushi-for-defending-his-thesis_yale.jpg",
      "date": "2024",
      "sortDate": "2024-01-01",
      "year": "2024",
      "precision": "year",
      "title": "Congratulating Choushi for Defending his thesis",
      "caption": "Congratulating Choushi for Defending his thesis.",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/094fa7f8-9b65-4600-a663-f113650344a9",
      "width": 3000,
      "height": 1799
    },
    {
      "id": "curated_event_025",
      "src": "Gallery/curated_lab_events_by_year/2024/001_manual-order_2024_2024-first-group-photo-after-lab-relocation_yale.jpg",
      "date": "2024",
      "sortDate": "2024-01-01",
      "year": "2024",
      "precision": "year",
      "title": "2024: First group photo after lab relocation",
      "caption": "2024: First group photo after lab relocation",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/baa0e545-6560-41ed-a8d5-837b16f56618",
      "width": 3000,
      "height": 2250
    },
    {
      "id": "curated_event_024",
      "src": "Gallery/curated_lab_events_by_year/2023/004_dated_july-2023_farewell-to-nickboy_utsw.jpeg",
      "date": "July 2023",
      "sortDate": "2023-07-01",
      "year": "2023",
      "precision": "month",
      "title": "Farewell to Nickboy",
      "caption": "Farewell to Nickboy, July 2023: Best Wishes for His Bright Future as a Graduate Student at the University of Colorado Boulder",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1328,
      "height": 929
    },
    {
      "id": "curated_event_023",
      "src": "Gallery/curated_lab_events_by_year/2023/003_dated_aacr-2023_aacr-2023_utsw.jpeg",
      "date": "AACR 2023",
      "sortDate": "2023-04-01",
      "year": "2023",
      "precision": "event",
      "title": "AACR 2023",
      "caption": "Mu Lab at the AACR 2023 annual meeting",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 4032,
      "height": 3024
    },
    {
      "id": "curated_event_022",
      "src": "Gallery/curated_lab_events_by_year/2023/002_dated_lunar-new-year-2023_new-year_utsw.jpg",
      "date": "Lunar New Year 2023",
      "sortDate": "2023-01-22",
      "year": "2023",
      "precision": "event",
      "title": "New Year",
      "caption": "We're Celebrating Lunar New Year 2023 with an Amazing Indian Buffet",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1228,
      "height": 1074
    },
    {
      "id": "curated_event_021",
      "src": "Gallery/curated_lab_events_by_year/2023/001_dated_new-year-2023_christmas_utsw.jpg",
      "date": "New Year 2023",
      "sortDate": "2023-01-01",
      "year": "2023",
      "precision": "event",
      "title": "Christmas",
      "caption": "Happy New Year 2023: We're Ringing in the New Year with Karaoke and Loads of Food",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1548,
      "height": 1080
    },
    {
      "id": "curated_event_020",
      "src": "Gallery/curated_lab_events_by_year/2022/003_dated_christmas-party-2022_christmas-party-2022_utsw.jpg",
      "date": "Christmas Party 2022",
      "sortDate": "2022-12-25",
      "year": "2022",
      "precision": "event",
      "title": "Christmas Party 2022",
      "caption": "Christmas Party 2022: Who Can Affix a Mustache to the Face of the Boss While Blindfolded?",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1440,
      "height": 1080
    },
    {
      "id": "curated_event_019",
      "src": "Gallery/curated_lab_events_by_year/2022/002_dated_halloween-2022_halloween-2022_utsw.jpg",
      "date": "Halloween 2022",
      "sortDate": "2022-10-31",
      "year": "2022",
      "precision": "event",
      "title": "Halloween 2022",
      "caption": "Halloween 2022 I didn’t mean this when I said we need to “open mind” at lab meeting.",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 3310,
      "height": 2546
    },
    {
      "id": "curated_event_018",
      "src": "Gallery/curated_lab_events_by_year/2022/001_manual-order_2022_our-second-paper-got-published_utsw.jpg",
      "date": "2022",
      "sortDate": "2022-09-01",
      "year": "2022",
      "precision": "year",
      "title": "Our second paper got published!",
      "caption": "Lab's Second Paper! Steakhouse lunch to celebrate our second paper that was published in Nature Cancer 2022!",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 2423,
      "height": 1675
    },
    {
      "id": "curated_event_017",
      "src": "Gallery/curated_lab_events_by_year/2020/001_manual-order_2020_mu-ping-lab-group-photo_utsw.jpeg",
      "date": "2020",
      "sortDate": "2020-04-01",
      "year": "2020",
      "precision": "year",
      "title": "Mu Ping Lab group photo",
      "caption": "Lab's First Paper! Celebrating our first paper that was published in Cancer Cell 2020!",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1486,
      "height": 998
    },
    {
      "id": "curated_event_016",
      "src": "Gallery/curated_lab_events_by_year/2019/009_manual-order_2019_gift-exchange-with-the-wu-lab-2019_utsw.jpeg",
      "date": "2019",
      "sortDate": "2019-12-01",
      "year": "2019",
      "precision": "year",
      "title": "Gift Exchange with the Wu Lab 2019",
      "caption": "Gift Exchange with the Wu Lab 2019 We all got some cool gifts from our Secret Santas!",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 2016,
      "height": 1230
    },
    {
      "id": "curated_event_015",
      "src": "Gallery/curated_lab_events_by_year/2019/008_dated_halloween-2019_mu-ping-lab-group-photo-with-halloween-costumes_yale.jpg",
      "date": "Halloween 2019",
      "sortDate": "2019-10-31",
      "year": "2019",
      "precision": "event",
      "title": "Mu Ping Lab group photo with Halloween costumes",
      "caption": "Halloween 2019 We're all too much fun to be scary.",
      "source": "Yale",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 768,
      "height": 500
    },
    {
      "id": "curated_event_014",
      "src": "Gallery/curated_lab_events_by_year/2019/007_manual-order_2019_ping-and-su-with-willie-nelson_utsw.jpeg",
      "date": "2019",
      "sortDate": "2019-08-01",
      "year": "2019",
      "precision": "year",
      "title": "Ping and Su with Willie Nelson",
      "caption": "Willie Nelson Ping and Su were personally invited to see their new friend, Willie Nelson, back stage and on his famous tour bus in 2019!",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1008,
      "height": 1345
    },
    {
      "id": "curated_event_012",
      "src": "Gallery/curated_lab_events_by_year/2019/005_manual-order_2019_ping-won-the-young-investigator-award-from-sbur_yale.jpg",
      "date": "2019",
      "sortDate": "2019-06-01",
      "year": "2019",
      "precision": "year",
      "title": "Ping won the Young Investigator Award from SBUR",
      "caption": "SBUR Young Investigator 2019 Ping won the Young Investigator Award from SBUR!",
      "source": "Yale",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 768,
      "height": 500
    },
    {
      "id": "curated_event_011",
      "src": "Gallery/curated_lab_events_by_year/2019/004_manual-order_2019_xiaoling-presents-her-poster-in-the-2019-nature-conference-in-nyc_utsw.jpg",
      "date": "2019",
      "sortDate": "2019-05-02",
      "year": "2019",
      "precision": "year",
      "title": "Xiaoling presents her poster in the 2019 Nature Conference in NYC",
      "caption": "Xiaoling Poster Xiaoling presents her poster in the 2019 Nature Conference in NYC",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1613,
      "height": 1210
    },
    {
      "id": "curated_event_010",
      "src": "Gallery/curated_lab_events_by_year/2019/003_manual-order_2019_julie-presenting-her-poster-at-the-nature-conference-in-nyc_utsw.jpg",
      "date": "2019",
      "sortDate": "2019-05-01",
      "year": "2019",
      "precision": "year",
      "title": "Julie presenting her poster at the Nature conference in NYC",
      "caption": "Julie's Poster in NYC Julie presenting her poster at the 2019 Nature conference in NYC",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1642,
      "height": 1233
    },
    {
      "id": "curated_event_009",
      "src": "Gallery/curated_lab_events_by_year/2019/002_manual-order_2019_mu-ping-lab-group-photo_utsw.jpeg",
      "date": "2019",
      "sortDate": "2019-03-01",
      "year": "2019",
      "precision": "year",
      "title": "Mu Ping Lab group photo",
      "caption": "Happy Birthday to Us! We celebrate the lab's first birthday, in 2019.",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1200,
      "height": 922
    },
    {
      "id": "curated_event_008",
      "src": "Gallery/curated_lab_events_by_year/2019/001_dated_2019-01_joint-new-year-lunch-2019_yale.jpg",
      "date": "2019-01",
      "sortDate": "2019-01-01",
      "year": "2019",
      "precision": "month/event",
      "title": "Joint New Year Lunch 2019",
      "caption": "Celebrating New Year with the Wu Lab",
      "source": "Yale",
      "descriptionSource": "Yale",
      "sourceUrl": "https://ysm-res.cloudinary.com/image/upload/v1/yms/prod/10378b08-c77d-4c83-ae06-7ff913184877",
      "width": 1024,
      "height": 614
    },
    {
      "id": "curated_event_007",
      "src": "Gallery/curated_lab_events_by_year/2018/006_manual-order_2018_mu-ping-lab-group-ramen-lunch_utsw.jpg",
      "date": "2018",
      "sortDate": "2018-12-15",
      "year": "2018",
      "precision": "year",
      "title": "Mu Ping Lab group ramen lunch",
      "caption": "Ichiro Ramen 2018 We left the boss at the lab for some quality ramen and quality time!",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1451,
      "height": 1089
    },
    {
      "id": "curated_event_006",
      "src": "Gallery/curated_lab_events_by_year/2018/005_dated_holiday-party-2018_group-photo-at-molecular-biology-department-holiday-party_yale.jpg",
      "date": "Holiday Party 2018",
      "sortDate": "2018-12-01",
      "year": "2018",
      "precision": "event",
      "title": "Group photo at Molecular Biology Department Holiday Party",
      "caption": "Holiday Party 2018 Celebrating in style at the Molecular Biology Department Holiday Party!",
      "source": "Yale",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1200,
      "height": 900
    },
    {
      "id": "curated_event_005",
      "src": "Gallery/curated_lab_events_by_year/2018/004_dated_halloween-2018_mu-ping-wearing-horse-mask-for-halloween_utsw.jpeg",
      "date": "Halloween 2018",
      "sortDate": "2018-10-31",
      "year": "2018",
      "precision": "event",
      "title": "Mu Ping wearing horse mask for Halloween",
      "caption": "The Horse Boss 2018 A horse came to the lab for Halloween dressed as Ping.",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 768,
      "height": 1024
    },
    {
      "id": "curated_event_004",
      "src": "Gallery/curated_lab_events_by_year/2018/003_dated_october-2018_mu-ping-lab-group-in-front-of-big-tex-statue_utsw.jpeg",
      "date": "October 2018",
      "sortDate": "2018-10-01",
      "year": "2018",
      "precision": "month",
      "title": "Mu Ping Lab group in front of Big Tex statue",
      "caption": "Big Tex, 2018 The lab goes on an outing to the State Fair of Texas in October 2018.",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 731,
      "height": 1200
    },
    {
      "id": "curated_event_003",
      "src": "Gallery/curated_lab_events_by_year/2018/002_manual-order_2018_mu-ping-lab-group-photo-on-their-first-outing_yale.jpg",
      "date": "2018",
      "sortDate": "2018-08-01",
      "year": "2018",
      "precision": "year",
      "title": "Mu Ping Lab group photo on their first outing",
      "caption": "First Lab Outing 2018 Our first lab outing to Breadwinners!",
      "source": "Yale",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1200,
      "height": 900
    },
    {
      "id": "curated_event_002",
      "src": "Gallery/curated_lab_events_by_year/2018/001_dated_july-2018_ping-with-edge-from-u2_utsw.jpeg",
      "date": "July 2018",
      "sortDate": "2018-07-01",
      "year": "2018",
      "precision": "month",
      "title": "Ping with Edge from U2",
      "caption": "The Edge Ping with his friend, Edge, at a U2 concert, July 2018",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 400,
      "height": 600
    },
    {
      "id": "curated_event_001",
      "src": "Gallery/curated_lab_events_by_year/2017/001_manual-order_2017_edge-from-u2-visits-pings-research-in-july-of-2017_utsw.jpeg",
      "date": "2017",
      "sortDate": "2017-01-01",
      "year": "2017",
      "precision": "year",
      "title": "Edge from U2 visits Ping's research in July of 2017",
      "caption": "Edge from U2 Edge visits Ping's research in 2017",
      "source": "UTSW",
      "descriptionSource": "UTSW",
      "sourceUrl": "https://web.archive.org/web/20240715123149/https://labs.utsouthwestern.edu/mu-ping-lab/photo-gallery",
      "width": 1242,
      "height": 1109
    }
  ],
  "datePending": [],
  "metadata": {
    "recordCount": 61,
    "order": "custom order from Gallery/editor_output/gallery-edits.json",
    "sourceManifest": "Gallery/curated_lab_events_by_year/curated_lab_events_manifest.json",
    "sourceOrder": "curated_lab_events_manual_order.csv"
  }
};
